
[2019-12-08 16:24:19] INFO [<module>: run_all.py, 6] ================================== 测试开始 ==================================
[2019-12-08 16:24:19] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-12-08 16:24:19] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2019-12-08 16:24:19] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2019-12-08 16:24:19] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2019-12-08 16:24:19] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "范冰冰","password":"123456"}
[2019-12-08 16:24:19] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2019-12-08 16:24:19] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2019-12-08 16:24:19] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-12-08 16:24:20] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2019-12-08 16:24:20] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2019-12-08 16:24:20] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2019-12-08 16:24:20] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2019-12-08 16:24:20] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2019-12-08 16:24:20] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2019-12-08 16:24:20] INFO [send_email: send_email.py, 44] 邮件发送完成！
[2019-12-08 16:24:20] INFO [<module>: run_all.py, 13] ================================== 测试结束 ==================================
